add new damask notebook for different analysis
pyiron/pyiron_continuum pull request #106
Opened 2022-02-23 12:40 UTC by yangbai90

2022-02-23 23:38 UTC, muh-hassani requested changes
@yangbai90, thanks for your PR. I have some minor suggestions.

2022-02-23 23:38 UTC, muh-hassani commented on pyiron_continuum/damask/damaskjob.py
> +        self.output.damask.export_VTK()
It is desirable to export the VTK files into `self.working_directory`. There might be a workaround. You can change the current working directory to `self.working_directory` and the after exporting the vk files, return to the old working directory.

2022-02-24 09:27 UTC, yangbai90 commented
@muh-hassani 
Hi Muhammad, I have update the related code according to your comments, now it should work.

Best,

Yang

2022-02-24 11:25 UTC, muh-hassani commented
@yangbai90, the notenook `damask_tutorial_elastoplasticity-powerlaw.ipynb` is failing during the tests. Can you check what the issue is? Thank you.

2022-02-24 12:11 UTC, yangbai90 commented
> @yangbai90, the notenook `damask_tutorial_elastoplasticity-powerlaw.ipynb` is failing during the tests. Can you check what the issue is? Thank you.

Hi @muh-hassani , now all the notebooks work fine on my local computer, maybe we could run the auto test  now. Thank you.

2022-02-24 14:08 UTC, muh-hassani commented
@yangbai90, there is an error irrelevant to your implementations, which causes our test to fail. I will take a look at it later in the afternoon.  If this error is solved, I will merge it.

2022-03-08 15:15 UTC, muh-hassani approved these changes

2022-03-08 15:15 UTC, merged