Fix integration workflow
pyiron/pyiron_continuum pull request #321
Opened 2024-06-03 14:19 UTC by niklassiemer

2024-06-03 14:28 UTC, samwaseda approved these changes
My manual test also passed (i.e. integration tests started running when I added `integration`). Good to go by me.

2024-06-03 14:31 UTC, samwaseda requested changes
Sorry I just realized that the notebooks are not running.

2024-06-03 14:33 UTC, samwaseda commented on .github/workflows/notebooks.yml
> +          exclusion-file: .ci_support/exclude
I didn't touch this line... But I guess it only added EOF so I don't think it disturbs

2024-06-03 14:33 UTC, samwaseda approved these changes

2024-06-04 08:15 UTC, mbruns91 commented
It seems like this this is working now, right?

2024-06-04 08:16 UTC, merged